nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.4.1.cjs
# npmScopes:
#     efebia-com:
#         npmAuthToken: '${EFEBIA_COM_NPM_TOKEN}'
#         npmRegistryServer: 'https://npm.pkg.github.com'
